services:
  - type: web
    name: mindsentinel-backend
    plan: free
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://admin:admin123@cluster.rpvq4sx.mongodb.net/mindsentinel?retryWrites=true&w=majority&appName=Cluster
